### ISSUE TITLE
数式表示に不具合があるようです

### ISSUE THREAD

**Issue by Mizuho32** [titech-ssr/wiki.rogiken.org#16]
プリアンブルに`:stem: latexmath`して`latexmath:[F^3RC]`みたいなことやったんですが、\(F^3RC\)が表示されちゃいました。ちなみにF<sup>3</sup>RCの表記はもちろん上付き文字に変えました。

**Comment by lo48576** [comment]
なるほど。それは私がmathjaxを有効化してなかったせいですね。

内部的な話をすると、このwikiではasciidoctorはコンテンツのhtmlしか吐かない感じなので、必要なjsのロードとかは別に指定してやる必要があって、それをしてなかったからでしょう。

あと一応F3RCは数式じゃないです、念のため

**Comment by Mizuho32** [comment]
必要なjsのロードってのはこちらから指示しないといけない感じですか

**Comment by lo48576** [comment]
サイト全体で一括管理するなら
https://github.com/titech-ssr/wiki.rogiken.org/blob/master/layouts/page-base.html
とかにタグを追加することになるし、ページ毎に指定するなら `++++` でhtml直書きしてscriptタグ追加です。

理想的には、frontmatter(ファイル先頭の属性指定)でmathjax有効化フラグを立てたページでのみ有効化するべきでしょうね(読み込み重そうだし、意図せず `\(` とかが数式化されると嫌なので)。
そういう方針でやってみます。

**Comment by Mizuho32** [comment]
読み込み重そうだよね・・・・
まぁ今のとこは++++が手っ取り早いですね
フラグ形式にするかどうかはそちらの裁量に任せます

**Comment by lo48576** [comment]
`++++` だと、依存先が古くなる/消えるものが出てくる可能性があったり、html以外への変換の可能性が失われたりと、あまり良い点がないので、情報の可搬性と管理の楽さの観点では、できればフラグでの拡張を利用してもらうのが望ましいです。

(まあどうせhtml以外では使わない気もしますが)
(なんならissue立てといてそのうち誰かに修正させるという手もありますね)

**Comment by Mizuho32** [comment]
うっすではフラグということで

**Comment by lo48576** [comment]
PR #18 のmergeにて閉じます。
