### ISSUE TITLE
サイドバーどうですか

### ISSUE THREAD

**Issue by phi16** [titech-ssr/wiki.rogiken.org#5]
ほしさがある(個人的感想)
特殊な1ページを作ってその内容を常に左に、というのがある程度楽そうな感じ(編集も)がありますが

**Comment by lo48576** [comment]
できるはずです。たぶんできます。
何を表示するかは決める必要がありますが、とりあえずﾌﾞﾖｸﾞの方がなんとかなったら実装してみます

**Comment by lo48576** [comment]
サイドバーの実体は、今のところ `/layout/part/sidebar.html` にあります
(というのも、eruby(erbだっけ？)とか使うと、「特定条件を満たす記事一覧」とか実装できて、普通の記事(asciidoc)より良さげだからです)
