### ISSUE TITLE
著作権関係事項

### ISSUE THREAD

**Issue by lo48576** [titech-ssr/wiki.rogiken.org#6]
単一記事に対しても多人数での編集が想定されるので、著作権関係の事項はちょっと面倒かもしれない。
基本CCにするとか、敢えて何も明示しないとか、いろいろ選択肢ありそうだけど、どうしましょう。

**Comment by 3tty0n** [comment]
基本的に参考文献を示しておくのがいいかと。

その辺のフォーマットを先に作っておくといいかもしれないですね。

**Comment by 3tty0n** [comment]
記事の末尾に

参考文献
・記事1(リンク)
・記事2(リンク)
...

というスタイルで書いておけばいいんじゃないかと。

**Comment by lo48576** [comment]
あーいえ、記事自体の権利についてです。
極めて個人的な思想では、広く知られることで役立てられる情報であれば[CCライセンス](https://creativecommons.jp/licenses/)とかでいい気はするのですが。
どうせ内輪ネタとか突っ込んでくるだろうし(むしろやってみたい)、そうなると一概に「出典明記すればこの記事は複製して公開(あるいは編集)してええで〜」みたいなのはちょっと危なかったりするのかな？と……

**Comment by 3tty0n** [comment]
> どうせ内輪ネタとか突っ込んでくるだろうし(むしろやってみたい)、そうなると一概に「出典明記すればこの記事は複製して公開(あるいは編集)してええで〜」みたいなのはちょっと危なかったりするのかな？と……

内輪的な内容になりそうであれば、ライセンスの明示はしなくてもよさそう(?)
このあたりは厳密にいくと面倒になりがちなので、常識の範囲内であればよいということにしましょう(!?)

**Comment by lo48576** [comment]
そーっすね、多くのwebページと同じく原則非明示でいい気がしてきました

**Comment by lo48576** [comment]
ひとまず閉じます。
